# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c331157824a21eb28e904abe8638e59b5f770e17c888a6bfc883c8b45287daca6042f6924d1f3f979c318332e5a257b2d75536b150bb88e89fe853d3a7ed771

test:
  secret_key_base: 922af3f5df294fe1411747583231c477455333f6ae9fd32874f58a096ac9925a6bb9c6def6d78884dd2796a3ba62ae69e2ce030d63c8da8ce8b287505063d235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
